--*MEMBERS, BOARDS 테이블 생성
--
-- - MEMBERS 테이블 
--
--1) MEMBER_ID 컬럼에 PRIMARY KEY 제약조건 설정.
--2) MEMBER_PWD 컬럼에 NOT NULL 제약조건 설정.
--3) MEMBER_NAME 컬럼에 가변 길이 문자열 30byte 설정.
--
--

-- MEMBERS 테이블 생성

CREATE TABLE MEMBERS(

MEMBER_ID VARCHAR2(20) PRIMARY KEY,
MEMBER_PWD VARCHAR2(20) NOT NULL,
MEMBER_NAME VARCHAR2(30), -- CHAR => VARCHAR2(30) 으로 바꿈
MEMBER_AGE NUMBER,
MEMBER_EMAIL VARCHAR2(50)
--PRIMARY KEY(MEMBER_ID) -- 테이블에는 하나의 기본 키만 가질 수 있습니다.

);

INSERT INTO MEMBERS
VALUES('D0','L2', '신짱구', '20', 'asdf@asdgf.com');
INSERT INTO MEMBERS
VALUES('D1','L2', '유리', '20', 'asdf@asdgf.com');
INSERT INTO MEMBERS
VALUES('D2','L2', '맹구', '20', 'asdf@asdgf.com');


SELECT * FROM MEMBERS;

-- - BOARDS 테이블 
--
--1) BOARD_NO 컬럼에 PRIMARY KEY 제약조건 설정.
--2) BOARD_WRITER 컬럼에 MEMBERS 테이블의 MEMBER_ID를 참조하는 FOREIGN KEY 제약조건 설정.
--3) BOARD_REG_DATE(작성일) 컬럼에 현재 시간으로 기본값 설정
-- BOARDS 테이블 생성


CREATE TABLE BOARDS(

BOARD_NO NUMBER PRIMARY KEY,
BOARD_TITLE VARCHAR2(100),
BOARD_CONTENT VARCHAR2(4000),
BOARD_WRITER VARCHAR2(20) FOREIGN KEY MEMBERS MEMBER_ID,
BOARD_REG_DATE DATE DEFAULT CURRENT_DATE

);


INSERT INTO BOARDS
VALUES('510','가나다ㄴㅁㅇㅎ', '래ㅜㅁㄴ애루ㅐㅁㄴ우래ㅜ', 'D0', DEFAULT);
INSERT INTO BOARDS
VALUES('511','가나다', 'ㅁ눙룸냉루ㅐㄴㅁ우래ㅜㅁㄴ애루ㅐㅁㄴ우래ㅜ', 'D1', DEFAULT);
INSERT INTO BOARDS
VALUES('512','가나다ㄴ류', 'ㅁ눙룸래ㅜㅁㄴ애루ㅐㅁㄴ우래ㅜ', 'D2', DEFAULT);

SELECT * FROM BOARDS;

ROLLBACK;


SELECT EMP_ID, EMP_NAME, DECODE(SUBSTR(EMP_NO,8,1),'1','F','2','M') 성별, 
		SALARY, JOB_NAME, NVL(DEPT_TITLE,'없음')
FROM EMPLOYEE
JOIN JOB USING(JOB_CODE)
JOIN DEPARTMENT ON (DEPT_ID = DEPT_CODE)
WHERE DECODE(SUBSTR(EMP_NO,8,1),'1','F','2','M') ='F'
AND SALARY BETWEEN 2000000 AND 4000000
ORDER BY SALARY ASC;

















